### ISSUE TITLE
jade-stream + stylus-stream in Express example

### ISSUE THREAD

**Issue by davisford** [socketstream/socketstream-0.4#18]
What are these packages?  I can't find them anywhere under your repo or in npm, or even references to them in any package.json file

https://github.com/socketstream/socketstream-0.4/blob/master/example_app/scripts/express_example.js#L11

**Comment by pocesar** [comment]
they are [ss-jade](https://github.com/socketstream/ss-stylus) and [ss-stream](https://github.com/socketstream/ss-jade), but they are for 3.x. maybe they are a modified version to work with 0.4? (havent tried myself)

**Comment by owenb** [comment]
Hey.

This example script is out of date now, sorry. I scrapped the streams idea completely as it didn't work out.

The asset_server.js file is the better way of doing this. It might be necessary to do something with Stylus, but we should (and do) just use the Jade express wrapper instead of creating our own.

**Comment by davisford** [comment]
Thanks @owenb -- I am interested in using Express -- as I want to also provide a standard HTTP web service API, and Express makes that so convenient, so if there's any other caveats I should be aware of with integrating ss-0.4 with Express, I'd love to hear about them.

**Comment by owenb** [comment]
You should be totally fine with Express. I spent a lot of time developing 0.4 with it in mind, so there shouldn't be any problems. Let me know how you get on and if you need any help there.
