### ISSUE TITLE
App Generator

### ISSUE THREAD

**Issue by paulbjensen** [socketstream/socketstream-0.4#20]
We need a way to run a command to generate the base structure of a 0.4 application.

I'm happy to have a go at implementing this feature, but before I proceed I'd like to find out:

1 - What files/folders to generate
2 - What optional arguments to support

**Comment by owenb** [comment]
So there are two ways to do this.
1. Do what we did in 0.3 and scaffold something which ends up looking very basic and pretty and easy to use.
2. Go more in the direction of Express and generate a larger, more verbose `app.js` file which exposes more of the mechanics under the hood. In this case, the generated `app.js` module would directly `require('prism')` at the top.

The second option initially looks more scary, but I believe could end up being a lot simpler to extend in the long run. As always, getting the balance right is key. Too much 'boilerplate' and it will put people off.

**Comment by davisford** [comment]
Even though I don't really use them myself -- I do like the approach taken by [yeoman](http://yeoman.io/), [brunch](http://brunch.io/), etc. where you have archetypes that you can choose from, and we could chuck out a recommended skeleton app with those flavors.  People seem to really dig this kind of thing, and it may help adoption.

**Comment by owenb** [comment]
It can be cool, but having too many combinations would be a nightmare to maintain without an automated means to check-out each combination out and run tests.

If in doubt, keep things simple. At least at first.

**Comment by arxpoetica** [comment]
My vote is for no. 2, go more in the direction of Express (since it's a familiar pattern). As for yeoman (or grunt for that matter) I think those are good options, but in my opinion we should just create documentation toward an approach like that, like, "if you're a grunter, yeomaner, or (oxford comma) bruncher," do this...

**Comment by davisford** [comment]
Yea, just a small point of clarification.  I wasn't proposing to use Yeoman or Brunch or whatever, I just like the idea of being able to write a recipe that constructs a skeleton project tailored for a particular scenario.  So, if I wanted to make a new SocketStream app with Angular + Jade + Stylus (my personal preference), I could write a re-useable recipe that the example app generator can run to do so.  I'm contrasting this against a fairly static set of app-generator options (Jade or no-Jade, etc.).  It would be nice to make it flexible so the community could write their own socket-stream archetypes and share them.

With respect to Grunt, I'm suggesting that it would be for development of ss itself.  We can use it to lint the code, test the code, integrate tests with a CI server, and create production and development builds, as well as package and deploy to npm.  End users of the framework don't need it, and it would be in the `devDependencies`.  Although it would be a prime candidate to consider for writing app archetypes and executing them in.

In any event, this is a wish-list and I'm more interested in trying to get ss feature complete :-)

**Comment by paulbjensen** [comment]
Some choices are inspired by random things, like this: http://www.youtube.com/watch?v=nmJKY59NX8o

number 2 it is.

**Comment by arxpoetica** [comment]
ha

**Comment by owenb** [comment]
@americanyak I totally agree with: 

> we should just create documentation toward an approach like that, like, "if you're a grunter, yeomaner, or (oxford comma) bruncher," do this..." 

Let's make the documentation based around recipes in this way.

@davisford That's cool. Happy to have grunt in the stack for dev. But let's not rush to include it for everyone else. This is not a tiny library - it's a mammoth beast!

@paulbjensen Brilliant :)

**Comment by RomanMinkin** [comment]
Guys, 

Please take a look at https://github.com/angular-ui/ui-router. There are `Grunt`/`jsdoc` bases documentation generator and a task for publishing. Looks pretty simple, so we can just add `markdown` stuff there:

**Gruntfile.js**

``` javascript
...
  grunt.registerTask('jsdoc', 'Generate documentation', function () {
    promising(this,
      system('node_modules/jsdoc/jsdoc -c jsdoc-conf.json -d \'' + grunt.config('builddir') + '\'/doc src')
    );
  });
...
```

So documentation will be in static HTML files, so no specific back-end requirements. `jsdoc` syntax supports in most editors/ide like [sublime-jsdocs](https://github.com/spadgos/sublime-jsdocs)  etc.

**Comment by davisford** [comment]
I did a branch that yanks in grunt (for ss dev only).  I built a few useful tasks and I'll try to push the branch up soon so people can take a look and decide if they are good with it.  One thing, though, since ss is now so distributed across so many smaller projects you may end up duplicating grunt tasks in each.  

I recently had this same issue (many repos / projects with dependencies and all built with grunt).  Instead of duplicating grunt tasks in each, a separate repo was made to hold common grunt tasks (wrappers around custom project stuff), and we pull that in via bower or npm pointing direct to the github url.  Something to consider.

**Comment by RomanMinkin** [comment]
@davisford , that's awesome! But it could be too complicated to have one more repo for grunt/common tasks. For example http://angular-ui.github.io/ separated projects into repos and added dependencies in each project for componets like

``` javascript
{
  "author": "AngularUI Team",
  "name": "angular-ui-utils",
  "description": "AngularUI Utilities - Companion Suite for AngularJS",
  "version": "0.0.3",
  "homepage": "http://angular-ui.github.com",
  "main": "./modules/utils.js",
  "dependencies": {
    "angular": ">= 1.0.2"
  },
  "devDependencies": {
    "angular-mocks": "~1.0.5",
    "jquery": ">=1.6",
    "angular-ui-docs": "angular-ui/angular-ui-docs"
  }
}
```

But yes this approach duplicates some tasks, but repos much stable itself because of it. 

Just my thoughts, it would be better to keep as less repos as possible.

**Comment by owenb** [comment]
I like that idea, @RomanMinkin 

When it's clear another repo is required, we should have one. But yes - the admin can become a real pain. Especially around tracking and answering issues.
