### ISSUE TITLE
Status of 0.4 vs 0.3

### ISSUE THREAD

**Issue by jcw** [socketstream/socketstream-0.4#6]
Hello Owen,

May I ask what the project time scale is, i.e. what your current expectation is as to when this code might be released as successor for 0.3?

I'm trying to figure out whether to base a new project on 0.4 or 0.3 - don't have enough experience yet to be able to contribute anything back, but am _very_ interested in the new design, EngineIO, etc. Given that I'm starting from scratch, working with 0.4 seems like a good idea, but the status of this project is currently not very clear to me. Is 0.4 still intended to supersede 0.3?

Thanks for creating and sharing this really interesting Node.js application infrastructure, btw.

-jcw

**Comment by owenb** [comment]
Hi Jean-Claude

Thanks for getting in touch.

I've not had as much time as I'd have hoped to work on 0.4 over the last few weeks, as I've been busy with other things; but that's slowly starting to change and I'm already beginning to work on 0.4 again on my laptop.

The honest answer is I don't know when 0.4 will be ready. There are two major problems still to solve:
1. Client-side templates. Right now this is not implemented in 0.4. I have left it out because I want to learn from 0.3 and implement this feature slightly differently. Not sure what that is yet though. I'm thinking about this problem now.
2. I love the new Websocket Services idea (the new take on Request Responders) but right now we have no Session support and I'm not yet sure how best to integrate it. I've been thinking about a new feature that may make this possible, but have yet to think it through and test it out.

So while work has now resumed on 0.4, we are still a long way away from a finished release.

I'd encourage you to go with 0.3 for now and stay actively involved with the development of 0.4 to suggest features and influence the future direction of things.

Take care,

Owen

**Comment by jcw** [comment]
Ok, thank you.

I'm currently looking into https://github.com/americanyak/ss-angular-demo - which ties it together with AngularJS.

The other big piece of the cake for me is how to share state across all clients and the server - maybe something like https://github.com/codeparty/racer could be used for that. Just a thought - I've yet to wrap my mind around it all.

Lots of things for me to learn, so it'll be a while before I will actually have anything of substance working.

Cheers,
-jcw

**Comment by jcw** [comment]
Great to see 0.4 progress, Owen. I have a couple of questions - not sure this is the proper place, but here goes:
1. now that asset & realtime serving have been decoupled: is it feasible to use nginx for assets, alongside node.js?
2. I'd like to use CoffeeScript, Jade, and Stylus, but still deliver & check-in the app with the pre-processed results, so that others are not forced to read the source code in those dialects - is there a simple way to fit this into SS 0.4?
3. the new modularity is great, I've been using a custom-made "briqs" mechanism for this in SS 0.3, but it suffered from having to place files in different places in the source tree (server-side code, client-side code, and templates) - can the new RTS API handle things such as client-side template files, while still keeping everything in a single folder / npm-managed package?
4. how does the RTS modularity compare to https://github.com/component/component#readme - is there overlap? can they be used together? or am I comparing apples and oranges?

Which all goes to show that a fool can ask more questions in a minute than a wise man can answer in an hour ;)

Anyway - great progress, all in all. The modular approach is a huge step forward, IMO. It may be a bit harder to see how everything fits together, but that should be easy to overcome with a few "seed" projects.

-jcw

**Comment by owenb** [comment]
Hi Jean-Claude

I'll have a go at answering:
1. You could definitely use either nginx or a CDN to host minified JS, CSS and images. But the root of your site (the main view) will need to go through Node to get a sesion cookie. At least that's true right now. I'd love to find a way to make this totally static too - but there are issues with Auth. Still need to look into that.
2. In a 0.4 app, for sure. In a Realtime Service Module - yes, we need to make that possible. It should be by design, but I have yet to work out all the asset serving stuff yet. It's on the list.
3. Good question. Each service is assigned a root directory where it can store any files it may need (e.g. /services/rpc/), so in theory yes. Realtime Services will be able to deliver all sorts of files to the client, so it should be possible to send client-side templates and more - but how this will all work in practice is yet to be decided.
4. Components are quite different - they don't have any of the realtime functionality, plus they require a separate build process which I'm really trying to avoid here. But I'm looking closely at the way things are done there and seeing if there is any overlap - maybe there will be on the client side stuff.

I totally agree splitting things up can be more confusing. I'm going to invest a lot of effort into diagrams, documentation and more to explain how everything fits together in the future. Also, if you're new to SocketStream it should be no harder to get up and running with the default chat demo screen with 0.4 than with 0.3 once we build the new project generator.

Thanks for the interest :)

Owen

**Comment by jcw** [comment]
Thx. I haven't thought through the authorisation stuff, my thinking so far is that everything static can be made public - only the real-time data (anything sent across though WS as JSON really) will need authentication/authorisation.

Just to give an idea of the modules I'd like to use, eventually: CoffeeScript translation, the Foundation CSS and AngularJS client-side frameworks, plotting with either flotr2 or nvd3, a simple home-made data-model sync, password-protected admin access, and then a whole slew of "briqs" - these are application-level modules which hook into the server and/or client, as well as serial ports, udp networking, etc. These modules rely on lots of domain-specific conventions and defaults to fill in as much of the inter-connectivity glue as possible, but hopefully they can be based on the RTS mechanism at some point.

I'm looking forward to switching over to SS 0.4 in the near future.

Thanks for sharing your designs and code,
-jcw

**Comment by jcw** [comment]
Looking at the runtime-generated server.js, I see that service wrappers get hard-coded into it, presumably on startup.

Not sure yet how this will fit in with my dynamic config, where modules can be installed and uninstalled ("activated" is perhaps a better term) from a client-side admin page. Note that this is only a limited form of dynamic loading - it would be ok to scan all modules on the server on startup, and generate wrappers once, even though these wrappers only get called when modules are actually installed. I'm not aiming (yet) for changing the available set of all modules in a running server, but just activating them should not require a server restart. Many modules are special-purpose, so it's likely people will only activate a small subset.

The reason for this is to also make HouseMon usable for non-programmers: there's no need to ever look at the code, yet it still allows the exchange and use of third-party modules by anyone.

Sorry if this all sounds a bit convoluted - I'm still struggling to find the proper terminology.
-jcw

**Comment by owenb** [comment]
Thanks. I had to laugh - most of the stack (Foundation, Angular, flotr2 in particular) are things I've been playing around with today with another project. I think these represent the best of the best at the moment.

It's going to be really hard to dynamically load-in new modules, especially if these modules then send additional code/modules to the client. The design of Browserify 2 makes this really difficult (more so than version 1).

There are possible workarounds (like loading new client-side code over the WebSocket) but not ones I'm in an rush to implement - at least for now. I want to get the basics right first.

**Comment by jcw** [comment]
> The design of Browserify 2 makes this really difficult

Perhaps the suggestion in issue #10 can help? - see https://github.com/webpack/webpack - it appears to use a very modular approach, just like the new RTS.

I've been using (and learning) Foundation, Angular, flotr2, etc in HouseMon, and am mighty impressed by each of them. It's very comforting to hear you confirm this, given the number of choices in JavaScript-land ...

**Comment by jcw** [comment]
While listening to your LXJS 2012 presentation, it occurred to me that what I'm trying to do is in a way "more" real-time than what SS is addressing. Well, in a crazy way, that is: what I would like is an _empty_ app, which gets developed, extended, and altered in real-time as well - i.e. not just a static set of design choices (with code, pages, and layout designed up front), but a real live app that changes without ever restarting the server. Or at least without ever losing the persistent state: restarts are fine, if things tie back into the files, assets, and database seamlessly.

Pretty steep goal. But it sort of explains things like why I'm controlling the server functionality through a client admin page, and installed / uninstalling modules on a server which rarely ever needs to go through a restart. The whole concept of starting and restarting becomes foreign, in fact.

**Comment by owenb** [comment]
Hi @jcw 

Yes, I think you're looking for something above and beyond SocketStream. Maybe one day we will have this functionality, but it's not something I want to prioritise right now - I'd rather get things like realtime models right first.

Owen

**Comment by paulbjensen** [comment]
Hi @jcw, is this discussion resolved for you?

**Comment by jcw** [comment]
Hello Paul, yes - I've now built my own solution ([jcw/primus-live](https://github.com/jcw/primus-live)). It's single-purpose, but works well for me.

This issue was really a bit of a mashup of various features, one of which was to maintain modules with client-side and server-side files (code, html, assets) all in one place, i.e. one folder per module instead of client + server folders, which I can now do. Another feature, the ability to install modules at run time, i.e. without browser reload is still limited because AngularJS doesn't support it (yet, they say). The third feature I've worked out is how to compile CoffeeScript, Jade, and Stylus on the fly without generating intermediate files on disk.

Thanks for following up, I'll close the issue.

-jcw
